config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  root "home#index"
  resources :recipes do 
    resources :amounts, only: [:create, :destroy]
  end
  resources :ingredients
  resources :weeklyplaner, only: [:show, :edit, :update] do
    resources :shopping_items, only: [:create, :update, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  
 end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
  has_many :amounts, dependent: :destroy
  has_many :ingredients, through: :amounts
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @amount = Amount.new(mengen: 1)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def recipe_params
    params.expect(recipe: [:title, :body])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% recipe.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.textarea :body %><br>
    <% recipe.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Neues Rezept speichern"%>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>Rezepte</h1>
<%= link_to "New Recipe", new_recipe_path %> <br>
<%= link_to "Ingredients", ingredients_path %> <br>

<ul>
  <% @recipes.each do |recipe|%>
  <li>
    <%= link_to recipe.title, recipe %>
  </li>
  <%end%>
</ul>

app/views/recipes/new.html.erb
<h1>Neues Rezept</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<h3>Zubereitung:</h3>
<p><%= simple_format(@recipe.body) %></p>
<p>
  <h3>Zutaten:</h3>
  <ul>
    <% @recipe.amounts.each do |amount|%>
  <li>
    <%= "#{amount.ingredient.name}, #{amount.mengen} #{amount.einheit}"%>    
    <%= link_to "Destroy", recipe_amount_path(@recipe, amount), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </li>
  <%end%>
  </ul>
  </p>

<div class="button-group">
  <%= link_to "🔙 Back", recipes_path, class: "btn" %>
  <%= link_to "✏️ Edit", edit_recipe_path(@recipe), class: "btn" %>
  <%= link_to "🗑️ Destroy", recipe_path(@recipe), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn" %>
</div>



<p>
<%= form_with model: [@recipe, @amount] do |form| %>
  <div>
    <%= form.label :Zutaten%>
    <%= form.collection_select :ingredient_id, Ingredient.all, :id, :name %>
  </div>
</p>
<p>
  <div>
    <%= form.label :mengen %>
    <%= form.text_field :mengen %>
    <% @amount.errors.full_messages_for(:mengen).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</p>
<p>
  <div>
    <%= form.label :einheit %>
    <%= form.select :einheit, ["g","ml","Stück","EL","TL", "Tasse"] %><br>
    <% @amount.errors.full_messages_for(:einheit).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</p>
<p>
  <div>
    <%= form.submit "➕ Zutat hinzufügen" %>
  </div>
</p>

  <%= link_to "Neue Zutat", new_ingredient_path %>
<% end %>