config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  root "home#index"
  resources :recipes do 
    resources :amounts, only: [:create, :destroy]
  end
  resources :ingredients
  resources :weeklyplaner, only: [:show, :edit, :update] do
    resources :shopping_items, only: [:create, :update, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check
  
 end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :amounts
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  def index
    @ingredients = Ingredient.all
  end 

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to @ingredient
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

    def ingredient_params
      params.expect(ingredient: [ :name ])
    end
end

app/views/ingredients/_form.html.erb
<%= form_with model: ingredient do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit product</h1>

<%= render "form", ingredient: @ingredient %>
<%= link_to "Cancel", @ingredient %>

app/views/ingredients/index.html.erb
<h1>Zutaten</h1>

<%= link_to "New ingredient", new_ingredient_path if authenticated? %> <br>
<%= link_to "Back to resepies", recipes_path %><br>
<%= link_to "Home", root_path %>

<ul>
  <% @ingredients.each do |ingredient| %>
    <li>
      <%= link_to ingredient.name, ingredient %>
    </li>
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>Neue Zutat</h1>

<%= render "form", ingredient: @ingredient %>

<div class="button-group">
  <%= link_to "Cancel", ingredients_path, class: "btn cancel" %>
</div>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<%= link_to "Back", ingredients_path %>
<% if authenticated? %>
<%= link_to "Edit", edit_ingredient_path(@ingredient) %>
<%= button_to "Delete", @ingredient, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<% end %>